// puzzle_runner.js — shared plumbing for the debug puzzle CLIs (solve.js,
// verify_solution.js): puzzle-source loading, solver build, solution-digit
// injection, and solution rendering. Owns the global-environment setup and the
// solver-module imports so importers don't repeat them.

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { ensureGlobalEnvironment } from '../../tests/helpers/test_env.js';
import { runSandboxToConstraint } from './sandbox_runner.js';

ensureGlobalEnvironment();

const PROJECT_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const { SudokuParser } = await import('../../js/sudoku_parser.js' + self.VERSION_PARAM);
const { SudokuBuilder } = await import('../../js/solver/sudoku_builder.js' + self.VERSION_PARAM);
const { LookupTables } = await import('../../js/solver/lookup_tables.js' + self.VERSION_PARAM);
const Collections = await import('../../data/collections.js' + self.VERSION_PARAM);
const { resolvePuzzleConfig } = await import('../../data/example_puzzles.js' + self.VERSION_PARAM);

// ============================================================================
// Puzzle source (--puzzle / --input / --input-file / --list)
// ============================================================================

export const allPuzzles = () => {
  const seen = new Set();
  const puzzles = [];
  for (const [collectionName, value] of Object.entries(Collections)) {
    if (!Array.isArray(value)) continue;
    value.forEach((entry, i) => {
      // Entries may be raw constraint strings, PUZZLE_INDEX puzzle names, or
      // { name, input } objects; the data layer resolves all three shapes.
      const config = typeof value.configFor === 'function'
        ? value.configFor(entry)
        : resolvePuzzleConfig(entry);
      if (!config || typeof config.input !== 'string') return;
      // Raw constraint strings have no distinct name; label them by position.
      const name = (!config.name || config.name === config.input)
        ? `${collectionName}#${i}` : config.name;
      if (seen.has(name)) return;
      seen.add(name);
      puzzles.push({ name, input: config.input });
    });
  }
  return puzzles;
};

export const findPuzzle = (query) => {
  const puzzles = allPuzzles();
  const exact = puzzles.find(p => p.name === query);
  if (exact) return exact;
  const lower = query.toLowerCase();
  const matches = puzzles.filter(p => p.name.toLowerCase().includes(lower));
  if (matches.length === 0) throw new Error(`No puzzle matches "${query}". Use --list to see names.`);
  if (matches.length > 1) {
    console.error(`"${query}" matched ${matches.length} puzzles; using "${matches[0].name}".`);
    console.error(`  (others: ${matches.slice(1, 6).map(m => m.name).join(', ')}${matches.length > 6 ? ', ...' : ''})`);
  }
  return matches[0];
};

// A puzzle's `input` may be a file path (leading '/'): a '.js' sandbox script
// that generates the constraint (executed here, once), or a raw constraint-text
// file. SudokuParser strips a text file's leading `#` comments.
const resolveInput = async (input) => {
  if (!input.startsWith('/')) return input;
  const text = readFileSync(join(PROJECT_ROOT, input), 'utf8');
  return input.endsWith('.js') ? runSandboxToConstraint(text) : text;
};

// args: { input, inputFile, puzzle } — exactly one set. Async because a script
// puzzle's constraint is generated by running its sandbox script.
export const loadPuzzle = async (args) => {
  if (args.input != null) return { name: 'custom', input: await resolveInput(args.input) };
  if (args.inputFile != null) return { name: args.inputFile, input: readFileSync(args.inputFile, 'utf8') };
  if (args.puzzle != null) {
    const p = findPuzzle(args.puzzle);
    return { ...p, input: await resolveInput(p.input) };
  }
  throw new Error('No puzzle specified. Use --puzzle, --input, or --input-file (or --list).');
};

// ============================================================================
// Solver build
// ============================================================================

// Parse a constraint string and build the solver. Returns the internal solver
// (with .run/.state/.counters) and its geometry.
export const buildSolver = (input) => {
  const constraint = SudokuParser.parseText(input);
  const resolved = SudokuBuilder.resolveConstraint(constraint);
  const solver = SudokuBuilder.build(resolved);
  const internal = solver._internalSolver;
  return { internal, geometry: internal._geometry };
};

// Append a full solution digit string as givens on a named cell group, in group
// order (`VG` for `new Var('G', ...)`, `CC` for chaos-construction regions, ...).
// For puzzles whose answer does not live in the main grid: the group must BE the
// answer, so its cell count has to match the solution length.
export const injectSolutionGivensForGroup = (input, digits, prefix) => {
  // Resolve the geometry only -- building a solver here would compile every
  // handler (and any NFA) a second time just to read the group's cell ids.
  const constraint = SudokuBuilder.resolveConstraint(SudokuParser.parseText(input));
  const geometry = constraint.getGeometry();
  geometry.addVarCellsForConstraints([].concat(...constraint.toMap().values()));

  const cells = geometry.varCellsForGroup(prefix);
  if (!cells) {
    const known = geometry.varCellGroups().map(g => g.prefix).join(', ') || 'none';
    throw new Error(
      `unknown cell group '${prefix}' (groups in this puzzle: ${known})`);
  }
  if (cells.length !== digits.length) {
    throw new Error(
      `group '${prefix}' has ${cells.length} cells but the solution has ` +
      `${digits.length} digits`);
  }
  let givens = '';
  for (let i = 0; i < digits.length; i++) {
    givens += `.~${geometry.makeCellIdFromIndex(cells[i])}_${digits[i]}`;
  }
  return input + givens;
};

// Append a full solution digit string as `.~RrCc_v` givens (main-grid cells,
// row-major). A '.' marks a cell that is not part of the answer -- an irregular
// grid modelled inside a rectangular Shape (a staircase, say) leaves holes -- and
// is left unpinned.
export const injectSolutionGivens = (input, digits) => {
  // Read the dimensions off the puzzle rather than inferring them from the
  // solution length, which can only ever describe a square grid.
  const constraint = SudokuBuilder.resolveConstraint(SudokuParser.parseText(input));
  const geometry = constraint.getGeometry();
  const { numRows, numCols } = geometry;
  if (digits.length !== numRows * numCols) {
    throw new Error(
      `solution has ${digits.length} chars but the grid is ${numRows}x${numCols} ` +
      `(${numRows * numCols} cells)`);
  }
  let givens = '';
  for (let i = 0; i < digits.length; i++) {
    if (digits[i] === '.') continue;
    // Cell ids use one base-17 character per coordinate (column 10 is 'a'), so
    // decimal interpolation would build invalid ids on grids wider than 9.
    givens += `.~${geometry.makeCellId(...geometry.splitCellIndex(i))}_${digits[i]}`;
  }
  return input + givens;
};

// ============================================================================
// Solution rendering
// ============================================================================

const decode = (mask, offset) =>
  (mask && !(mask & (mask - 1))) ? String(LookupTables.toOffsetValue(mask, offset)) : '?';

const printDigitGrid = (geometry, grid) => {
  for (let r = 0; r < geometry.numRows; r++) {
    const row = [];
    for (let c = 0; c < geometry.numCols; c++) {
      row.push(decode(grid[r * geometry.numCols + c], geometry.valueOffset).padStart(2));
    }
    console.log(row.join(' '));
  }
};

const printVarGrid = (geometry, grid, cells, columns) => {
  const numRows = Math.ceil(cells.length / columns);
  for (let r = 0; r < numRows; r++) {
    const row = [];
    for (let c = 0; c < columns; c++) {
      const idx = r * columns + c;
      if (idx >= cells.length) break;
      row.push(decode(grid[cells[idx]], 0).padStart(2));
    }
    console.log(row.join(' '));
  }
};

export const printSolution = (geometry, grid, solutionNum) => {
  console.log(`\n=== Solution ${solutionNum} ===`);
  printDigitGrid(geometry, grid);

  for (const group of geometry.varCellGroups()) {
    if (group.hidden) continue;
    console.log(`\n[${group.prefix}] ${group.label}:`);
    if (group.columns) {
      printVarGrid(geometry, grid, group.cells, group.columns);
    } else {
      for (const cell of group.cells) {
        const id = geometry.makeCellIdFromIndex(cell);
        console.log(`  ${id} = ${decode(grid[cell], 0)}`);
      }
    }
  }
};
